import type { ModuleDef, ModuleKind, MonsterDef, MonsterKind } from './types'

export const MONSTERS: Record<MonsterKind, MonsterDef> = {
  slime: {
    kind: 'slime',
    name: '错字史莱姆',
    hp: 64,
    speed: 0.53,
    reward: 3,
    leakDamage: 12,
    color: '#3d6b4f',
  },
  beetle: {
    kind: 'beetle',
    name: '近义词甲虫',
    hp: 145,
    speed: 0.37,
    reward: 6,
    leakDamage: 28,
    color: '#8a5a2b',
  },
  ghost: {
    kind: 'ghost',
    name: '同音异形鬼',
    hp: 84,
    speed: 0.68,
    reward: 7,
    leakDamage: 18,
    color: '#5a6b8a',
  },
}

/** 六种颠覆性模组：外形与机制各不相同 */
export const MODULES: Record<ModuleKind, ModuleDef> = {
  quill: {
    kind: 'quill',
    name: '墨羽',
    desc: '羽笔发射墨针，单体高速',
    cost: 48,
    range: 1.85,
    damage: 16,
    cooldown: 0.72,
    color: '#c45c3e',
  },
  spore: {
    kind: 'spore',
    name: '孢囊',
    desc: '蘑菇弹溅射孢子云',
    cost: 82,
    range: 1.48,
    damage: 9,
    cooldown: 1.15,
    aoe: 0.92,
    color: '#3d8a4a',
  },
  snare: {
    kind: 'snare',
    name: '藤网',
    desc: '藤蔓脉冲减速路过怪',
    cost: 44,
    range: 1.2,
    damage: 0,
    cooldown: 0.4,
    slowFactor: 0.5,
    slowDuration: 1.25,
    color: '#6b8a2f',
  },
  beam: {
    kind: 'beam',
    name: '荧光笔',
    desc: '直线穿透光束，路径上全打',
    cost: 95,
    range: 2.35,
    damage: 11,
    cooldown: 1.35,
    beamWidth: 0.28,
    color: '#e0a820',
  },
  chain: {
    kind: 'chain',
    name: '谐音链',
    desc: '电弧在怪之间跳跃',
    cost: 110,
    range: 1.7,
    damage: 13,
    cooldown: 1.05,
    chainJumps: 3,
    chainRange: 1.55,
    color: '#5a8fd4',
  },
  stamp: {
    kind: 'stamp',
    name: '爆印',
    desc: '印章砸地，范围爆发伤害',
    cost: 120,
    range: 1.35,
    damage: 22,
    cooldown: 1.55,
    color: '#c43e5c',
  },
}

export const MODULE_ORDER: ModuleKind[] = ['quill', 'spore', 'snare', 'beam', 'chain', 'stamp']
