CREATE DATABASE IF NOT EXISTS wordbeat
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE wordbeat;

CREATE TABLE IF NOT EXISTS word_packs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  source VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS words (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pack_id INT UNSIGNED NOT NULL,
  word VARCHAR(128) NOT NULL,
  meaning VARCHAR(512) NOT NULL,
  UNIQUE KEY uq_pack_word (pack_id, word),
  CONSTRAINT fk_words_pack FOREIGN KEY (pack_id) REFERENCES word_packs(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS levels (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  subtitle VARCHAR(255) NOT NULL,
  map_cols INT UNSIGNED NOT NULL,
  map_rows INT UNSIGNED NOT NULL,
  start_gold INT UNSIGNED NOT NULL,
  lives INT UNSIGNED NOT NULL,
  pack_id INT UNSIGNED NOT NULL,
  path_json JSON NOT NULL,
  unlocked_modules_json JSON NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_levels_pack FOREIGN KEY (pack_id) REFERENCES word_packs(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS level_waves (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  level_id INT UNSIGNED NOT NULL,
  wave_index INT UNSIGNED NOT NULL,
  delay_sec DECIMAL(6,2) NOT NULL,
  spawns_json JSON NOT NULL,
  UNIQUE KEY uq_level_wave (level_id, wave_index),
  CONSTRAINT fk_waves_level FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE CASCADE
) ENGINE=InnoDB;
